print('content-type:text/html\r\n\r\n')
print('<!DOCTYPE HTML!>')
print('<!html lang="en>')
print('<head>')
print('<meta charset="UTF-8>')
print('<title> python response</title>')
print('</head>')
print('<body>')
print('<h1> hello from python online!</h1>')
print('</body>')
print('</html>')
